module.exports={
    ankush:{
        password:"ankush123",
        role:"admin"
    },
    Incharge1:{
        password:"incharge1",
        incharge:"Incharge1",
        role:"user",
        gangs:["DTM19","DTM20","DTM21","machine","contractual"],
        unit:"BXA"
    },
    Incharge2:{
        password:"incharge2",
        incharge:"Incharge2",
        role:"user",
        gangs:["DTM22","DTM23","DTM24","machine","contractual"],
        unit:"BXA"
    },
    Incharge3:{
        password:"incharge3",
        incharge:"Incharge3",
        role:"user",
        gangs:["DTM25","DTM26","DTM27","machine","contractual"],
        unit:"BXA"
    },
    Incharge4:{
        password:"incharge4",
        incharge:"Incharge4",
        role:"user",
        gangs:["DTM28","DTM29","DTM30","machine","contractual"],
        unit:"BMY"
    },
    Incharge5:{
        password:"incharge5",
        incharge:"Incharge5",
        role:"user",
        gangs:["DTM31","DTM32","DTM33","machine","contractual"],
        unit:"BMY"
    },
    Incharge6:{
        password:"incharge6",
        incharge:"Incharge6",
        role:"user",
        gangs:["DTM34","DTM35","DTM36","machine","contractual"],
        unit:"BMY"
    }
}

